FROM codeberg.org/forgejo/forgejo:1.21

ARG FORGEJO_DB_NAME
ARG FORGEJO_DB_USER
ARG FORGEJO_DB_PASSWORD
ARG FORGEJO_DB_HOST
ARG FORGEJO_DB_PORT
ARG FORGEJO_HTTP_PORT
ARG FORGEJO_SSH_PORT
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASSWORD
ARG SMTP_FROM
ARG SMTP_TLS
ARG USER_UID
ARG USER_GID
ARG DB_TYPE
ARG MAILER_ENABLED


ENV USER_UID=$USER_UID
ENV USER_GID=$USER_GID
ENV DB_TYPE=$DB_TYPE
ENV DB_HOST=$FORGEJO_DB_HOST
ENV DB_PORT=$FORGEJO_DB_PORT
ENV DB_NAME=$FORGEJO_DB_NAME
ENV DB_USER=$FORGEJO_DB_USER
ENV DB_PASSWD=$FORGEJO_DB_PASSWORD
ENV MAILER_ENABLED=MAILER_ENABLED
ENV MAILER_HOST=$SMTP_HOST
ENV MAILER_PORT=$SMTP_PORT
ENV MAILER_USER=$SMTP_USER
ENV MAILER_PASSWD=$SMTP_PASSWORD
ENV MAILER_FROM=$SMTP_FROM
ENV MAILER_IS_TLS_ENABLED=$SMTP_TLS

