name: CI Vault Login + Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq unzip curl gnupg
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault -y

      - name: Login to Vault & Export Secrets
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_USERNAME: ${{ secrets.VAULT_USERNAME }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          export VAULT_ADDR="$VAULT_ADDR"
          TOKEN=$(vault login -method=userpass \
            username="$VAULT_USERNAME" \
            password="$VAULT_PASSWORD" \
            -format=json | jq -r '.auth.client_token') || exit 1
          export VAULT_TOKEN="$TOKEN"
          for key in FORGEJO_DB_NAME FORGEJO_DB_USER FORGEJO_DB_PASSWORD FORGEJO_DB_HOST FORGEJO_DB_PORT \
                     FORGEJO_HTTP_PORT FORGEJO_SSH_PORT SMTP_HOST SMTP_PORT SMTP_USER SMTP_PASSWORD \
                     SMTP_FROM SMTP_TLS USER_UID USER_GID DB_TYPE MAILER_ENABLED; do
            echo "$key=$(vault kv get -field=$key secret/FORGEJO)" >> $GITHUB_ENV
          done

      - name: Build Forgejo Image
        run: |
          docker buildx build -t forgejo-secure:latest \
            --build-arg FORGEJO_DB_NAME=$FORGEJO_DB_NAME \
            --build-arg FORGEJO_DB_USER=$FORGEJO_DB_USER \
            --build-arg FORGEJO_DB_PASSWORD=$FORGEJO_DB_PASSWORD \
            --build-arg FORGEJO_DB_HOST=$FORGEJO_DB_HOST \
            --build-arg FORGEJO_DB_PORT=$FORGEJO_DB_PORT \
            --build-arg FORGEJO_HTTP_PORT=$FORGEJO_HTTP_PORT \
            --build-arg FORGEJO_SSH_PORT=$FORGEJO_SSH_PORT \
            --build-arg SMTP_HOST=$SMTP_HOST \
            --build-arg SMTP_PORT=$SMTP_PORT \
            --build-arg SMTP_USER=$SMTP_USER \
            --build-arg SMTP_PASSWORD=$SMTP_PASSWORD \
            --build-arg SMTP_FROM=$SMTP_FROM \
            --build-arg SMTP_TLS=$SMTP_TLS \
            --build-arg USER_UID=$USER_UID \
            --build-arg USER_GID=$USER_GID \
            --build-arg DB_TYPE=$DB_TYPE \
            --build-arg MAILER_ENABLED=$MAILER_ENABLED \
            ./git-action-deployment

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy with Docker Compose
        run: |
          cd dbeaver
          docker-compose up -d
