name: CI Vault Login Example

on:
  push:
    branches: [main]

jobs:
  vault-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Login to Vault
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          vault login -method=userpass \
            username=${{ secrets.VAULT_USERNAME }} \
            password=${{ secrets.VAULT_PASSWORD }}

      - name: Read Secrets from Vault
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export TOKEN=$(vault login -method=userpass \
            username=${{ secrets.VAULT_USERNAME }} \
            password=${{ secrets.VAULT_PASSWORD }} \
            -format=json | jq -r '.auth.client_token')

          SECRET_JSON=$(vault kv get -format=json -token=$TOKEN secret/myapp/config)
          echo $SECRET_JSON | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Use Secrets
        run: |
          echo "DATABASE USER: $DB_USER"
          echo "DATABASE PASSWORD: $DB_PASSWORD"


      - name: 🔢 Logging into Vault & set variables
        run: |
            vault login -method=userpass username=${{ env.VAULT_USERNAME  }} password=${{ env.VAULT_PASSWORD }}
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_DB_NAME | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_DB_USER | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_DB_PASSWORD | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_DB_HOST | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_DB_PORT | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_HTTP_PORT | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w FORGEJO_SSH_PORT | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_HOST | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_PORT | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_USER | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_PASSWORD | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_FROM | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w SMTP_TLS | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w USER_UID | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w USER_GID | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w DB_TYPE | awk '{print $1"="$2}'  >> $GITHUB_ENV
            vault kv get Dev-secret/forgejo_smtp | grep -w MAILER_ENABLED | awk '{print $1"="$2}'  >> $GITHUB_ENV
            
      - name: Build Forgejo Image-forcicd
        run: |
          docker build -t forgejo-secure:latest \
            --build-arg FORGEJO_DB_NAME=$FORGEJO_DB_NAME \
            --build-arg FORGEJO_DB_USER=$FORGEJO_DB_USER \
            --build-arg FORGEJO_DB_PASSWORD=$FORGEJO_DB_PASSWORD \
            --build-arg FORGEJO_DB_HOST=$FORGEJO_DB_HOST \
            --build-arg FORGEJO_DB_PORT=$FORGEJO_DB_PORT \
            --build-arg FORGEJO_HTTP_PORT=$FORGEJO_HTTP_PORT \
            --build-arg FORGEJO_SSH_PORT=$FORGEJO_SSH_PORT \
            --build-arg SMTP_HOST=$SMTP_HOST \
            --build-arg SMTP_PORT=$SMTP_PORT \
            --build-arg SMTP_USER=$SMTP_USER \
            --build-arg SMTP_PASSWORD=$SMTP_PASSWORD \
            --build-arg SMTP_FROM=$SMTP_FROM \
            --build-arg SMTP_TLS=$SMTP_TLS \ 
            --build-arg USER_UID=$USER_UID \
            --build-arg USER_GID=$USER_GID \
            --build-arg DB_TYPE=$DB_TYPE \
            --build-arg MAILER_ENABLED=MAILER_ENABLED \

            ./dbeaver
             # 🔧 Step 6: Configure AWS Credentials
      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 🔑 Step 7: Login to Amazon ECR
      - name: 🔑 Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 📤 Step 8: Tag and Push Docker Image to ECR
      - name: 📦 Push Docker Image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ env.COMMIT_SHA_SHORT }}
        run: |
          docker tag forgejo-secure:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      - name: Deploy with Docker Compose
        run: |
          cd dbeaver
          docker-compose up -d
